#!/bin/sh -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    for alt in startovd-kde startovd-xfce; do
        update-alternatives --install /usr/bin/startovd \
            startovd /usr/bin/$alt 60
    done

    update-alternatives --set startovd /usr/bin/startovd-xfce
fi

#DEBHELPER#

exit 0
