package org.ulteo.ovd.standalone;

import java.net.URL;
import javax.swing.JPanel;

public class LoadingPanel extends JPanel {

	private Client ovd;

	/** Creates new form NewJPanel */
	public LoadingPanel(Client main_instance) {
		this.ovd = main_instance;
		initComponents();
	}


	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

		URL icon_url = this.getClass().getResource("/ressources/ulteo.big.png");
		jLabel1.setIcon(new javax.swing.ImageIcon(icon_url)); // NOI18N

		icon_url = this.getClass().getResource("/ressources/loader.gif");
		jLabel2.setIcon(new javax.swing.ImageIcon(icon_url)); // NOI18N

		jLabel3.setText("Loading Session ..."); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
				.addGap(39, 39, 39)
				.addComponent(jLabel1)
				.addContainerGap(104, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				.addGap(132, 132, 132)
				.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
				.addGap(18, 18, 18)
				.addComponent(jLabel2)
				.addGap(157, 157, 157)
			)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(29, 29, 29)
					.addComponent(jLabel1)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
					.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				)
				.addContainerGap(45, Short.MAX_VALUE)
			)
		);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration
}
