#! /usr/bin/python
# -*- coding: UTF-8 -*-

# Copyright (C) 2010-2011 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010
# Author Julien LANGLOIS <julien@ulteo.com> 2011
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import os, sys, shutil, pysvn
import time

path = os.path.dirname( os.path.realpath( __file__ ) )

# Detect the version
if os.environ.has_key("OVD_VERSION"):
    version = os.environ["OVD_VERSION"]
else:
    c = pysvn.Client()
    revision = c.info(path)["revision"].number
    if sys.platform == "win32":
        version = "99.99.0.%05d"%(revision)
    else:
        version = "99.99+svn%05d"%(revision)

# OS detection
if sys.platform == "linux2":
    platform_dir = "Linux"
elif sys.platform == "win32":
    platform_dir = "Windows"
else:
   raise Exception("No supported platform")


# Set the Platform directory
path_virtual = os.path.join(path, "ovd_shells", "Platform")
path_real    = os.path.join(path, "ovd_shells", "Platform."+platform_dir)
if os.path.exists(path_virtual):
    shutil.rmtree(path_virtual)
shutil.copytree(path_real, path_virtual)


f = file(os.path.join(path, "setup.py.in"), "r")
content = f.read()
f.close()

content = content.replace("@VERSION@", str(version))
content = content.replace("@YEAR@", time.strftime("%Y"))

f = file(os.path.join(path, "setup.py"), "w")
f.write(content)
f.close()
