#!/bin/sh -e

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    if [ -d .svn ]; then
      revision=$(LC_ALL=C svn info . | awk '/^Revision: / {printf "%05d\n", $2}')
    else
      revision=0
    fi
    version="99.99+svn$revison"
fi

sed -e "s/@VERSION@/${version}/g" < configure.ac.in > configure.ac

xdt-autogen $@

# hack for certain intltoolize version that doesn't create these files
touch intltool-extract.in intltool-merge.in intltool-update.in
