#!/bin/sh

# Copyright (C) 2010, 2012 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010
# Author David PHAM-VAN <d.pham-van@ulteo.com> 2012
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    version=$(cat VERSION | head -n 1)~dev
fi

sed -e "s/@VERSION@/${version}/g" configure.ac.in > configure.ac

autoreconf -vfi && ./configure --without-ulteo-applets $@

python compile_js_css.py
