#!/bin/sh

# $XDG_CONFIG_HOME defines the base directory relative to which user specific 
# configuration files should be stored. If $XDG_CONFIG_HOME is either not set 
# or empty, a default equal to $HOME/.config should be used.
if test "x$XDG_CONFIG_HOME" = "x" ; then
  XDG_CONFIG_HOME=$HOME/.config
fi
[ -d "$XDG_CONFIG_HOME" ] || mkdir "$XDG_CONFIG_HOME"

# $XDG_CACHE_HOME defines the base directory relative to which user specific 
# non-essential data files should be stored. If $XDG_CACHE_HOME is either not 
# set or empty, a default equal to $HOME/.cache should be used.
if test "x$XDG_CACHE_HOME" = "x" ; then
  XDG_CACHE_HOME=$HOME/.cache
fi
[ -d "$XDG_CACHE_HOME" ] || mkdir "$XDG_CACHE_HOME"

# For now, start with an empty list
XRESOURCES=""

# Has to go prior to merging Xft.xrdb, as its the "Defaults" file
test -r "/etc/xdg/xfce4/Xft.xrdb" && XRESOURCES="$XRESOURCES /etc/xdg/xfce4/Xft.xrdb"
test -r $HOME/.Xdefaults && XRESOURCES="$XRESOURCES $HOME/.Xdefaults"

BASEDIR=$XDG_CONFIG_HOME/xfce4
if test -r "$BASEDIR/Xft.xrdb"; then
  XRESOURCES="$XRESOURCES $BASEDIR/Xft.xrdb"
elif test -r "$XFCE4HOME/Xft.xrdb"; then
  mkdir -p "$BASEDIR"
  cp "$XFCE4HOME/Xft.xrdb" "$BASEDIR"/
  XRESOURCES="$XRESOURCES $BASEDIR/Xft.xrdb"
fi

# merge in X cursor settings
test -r "$BASEDIR/Xcursor.xrdb" && XRESOURCES="$XRESOURCES $BASEDIR/Xcursor.xrdb"

# ~/.Xresources contains overrides to the above
test -r "$HOME/.Xresources" && XRESOURCES="$XRESOURCES $HOME/.Xresources"

# load all X resources (adds /dev/null to avoid an empty list that would hang the process)
cat /dev/null $XRESOURCES | xrdb -nocpp -merge -

# load local modmap
test -r $HOME/.Xmodmap && xmodmap $HOME/.Xmodmap

# Use dbus-launch if installed.
if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
        dbuslaunch=`which dbus-launch`
        if test x"$dbuslaunch" != x"" -a x"$dbuslaunch" != x"no"; then
                eval `$dbuslaunch --sh-syntax --exit-with-session`
        fi
fi

# Sleep so that to ensure we avoid dead-locking in xcblib. (lp bug #232364)
sleep 1

# Launch xscreensaver (if available), but only as non-root user
if test $UID -gt 0 -a -z "$VNCSESSION"; then
    if test x"`which xscreensaver 2>/dev/null`" != x""; then
        xscreensaver -no-splash &
    elif test x"`which gnome-screensaver 2>/dev/null`" != x""; then
        gnome-screensaver &
    fi
fi

# gtk config
if [ ! -e $HOME/.gtk_qt_engine_rc ] && [ -e /usr/share/ulteo-kde-default-settings/.gtk_qt_engine_rc ]
then
 cp -f /usr/share/ulteo-kde-default-settings/.gtk_qt_engine_rc $HOME
fi

if [ ! -e $HOME/.gtkrc-2.0 ] && [ -e /usr/share/ulteo-kde-default-settings/.gtkrc-2.0 ]
then
 cp -f /usr/share/ulteo-kde-default-settings/.gtkrc-2.0 $HOME
fi

# automatically open an application if needed
if [ "$DOC" != "" ] || [ "$APP" != "" ]; then
  if [ "$APP" = "" ]; then APP="xdg-open"; fi # Open the default application for the document type. Needs xdg-utils.
  if [ "$APP" = "oowriter" ]; then APP="soffice -writer"; fi
  if [ "$APP" = "oocalc" ]; then APP="soffice -calc"; fi
  if [ "$APP" = "ooimpress" ]; then APP="soffice -impress"; fi
  if [ "$APP" = "oomath" ]; then APP="soffice -math"; fi
  if [ "$APP" = "oobase" ]; then APP="soffice -base"; fi
  if [ "$APP" = "oodraw" ]; then APP="soffice -draw"; fi

  $APP $DOC &
fi

xfce4-session

if test $kill_sshagent -eq 1; then
    eval `$sshagent -k`
fi

exit 0

