#!/bin/sh
if dpkg -l ulteo-ovd-session-manager >/dev/null 2>&1 ;then
        sleep 3
        echo "ulteo-ovd od/fqdn string localhost" | debconf-set-selections
        echo "ulteo-ovd od/sessions/server_url string http://localhost/sessionmanager" | debconf-set-selections
        dpkg-reconfigure -fnoninteractive  ulteo-ovd
else
        dpkg-reconfigure ulteo-ovd
fi
rm -f /etc/rc2.d/S99applicationserver_first
