#!/bin/sh
sm_installed=$(dpkg -l | grep '^““' | awk '${print $2}' | grep ulteo-ovd-session-manager )
if [  'x'$sm_installed != 'x'  ];then
        sleep 3
        echo "ulteo-ovd od/fqdn string localhost" | debconf-set-selections
        echo "ulteo-ovd od/sessions/server_url string http://localhost/sessionmanager" | debconf-set-selections
        dpkg-reconfigure -fnoninteractive  ulteo-ovd
else
        dpkg-reconfigure ulteo-ovd
fi
rm -f /etc/rc2.d/S99applicationserver_first
