#! /usr/bin/python

import os
import pysvn

# Detect the version
if os.environ.has_key("OVD_VERSION"):
	version = os.environ["OVD_VERSION"]

else:
	c = pysvn.Client()
	revision = c.info(".")["revision"].number
	version = "99.99~trunk+svn%05d"%(revision)

f = file("configure.ac.in", "r")
content = f.read()
f.close()

content = content.replace("@REVISION@", str(version))

f = file("configure.ac", "w")
f.write(content)
f.close()
