
DATA=\
	gfxboot1.png \
	gfxboot2.png \
	splash_livecd.png \
	system_prompt.png \
	ubiquity_identity_info.png \
	ubiquity_install_system.png \
	ubiquity_keyboard_layout.png \
	ubiquity_language.png \
	ubiquity_ovd_configuration.png \
	ubiquity_partman.png \
	ubiquity_restart.png \
	ubiquity_summary.png \
	ubiquity_timezone.png \

all:

install:
	install -d 		$(DIST)
	install $(DATA)		$(DIST)


