#!/bin/sh -e

if [ -d /etc/apache2/conf-available ]; then
    A2CONFDIR=/etc/apache2/conf-available
else
    A2CONFDIR=/etc/apache2/conf.d
fi

# remove apache2 config link
which a2disconf && a2disconf ovd-administration-console
rm -f $A2CONFDIR/ovd-administration-console.conf

# reload apache
if apache2ctl configtest 2>/dev/null; then
    invoke-rc.d apache2 reload || true
else
    echo "Your apache2 configuration is broken, so we're not restarting it for you."
fi

#DEBHELPER#

exit 0
