#!/bin/sh
# Copyright (c) 2010 Ulteo SAS.
#
# Author: Julien LANGLOIS <julien@ulteo.com>
#
### BEGIN INIT INFO
# Provides:          ulteo-ovd-subsystem
# Required-Start: $network $remote_fs
# Required-Stop: $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Ulteo OVD subsystem
# Description:       Start Ulteo OVD subsystem and needed services
### END INIT INFO

. /etc/rc.status

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

# First reset status of this service
rc_reset

# useless for now...
[ -f $sysconfdir/ulteo-ovd-subsystem ] && . $sysconfdir/ulteo-ovd-subsystem
[ "$START" = no ] && exit 0


CONF=/etc/ulteo/subsystem.conf
[ -f "$CONF" ] && . $CONF
[ -z "$CHROOT" ] && CHROOT=/opt/ulteo

test -d "$CHROOT" || exit 5

do_start() {
    mount -t proc none $CHROOT/proc
    mount -t devpts none $CHROOT/dev/pts

    chroot $CHROOT /etc/init.d/cups start
    chroot $CHROOT /etc/init.d/xrdp start
    chroot $CHROOT /etc/init.d/ulteo-ovd-slaveserver start
}

do_stop() {
    chroot $CHROOT /etc/init.d/ulteo-ovd-slaveserver stop
    chroot $CHROOT /etc/init.d/xrdp stop
    chroot $CHROOT /etc/init.d/cups stop

    umount $CHROOT/dev/pts || true
    umount $CHROOT/proc || true
}

case $1 in
    start)
	echo -n "Starting Ulteo OVD subsystem"
        do_start
	rc_status -v
        ;;
    stop)
        echo -n "Stopping Ulteo OVD subsystem"
        do_stop
	rc_status -v
        ;;
    restart|reload|force-reload)
        echo -n "Re-starting Ulteo OVD subsystem"
        do_stop && sleep 1 && do_start
	rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0
