#!/bin/sh
# Copyright (C) 2008-2010 Ulteo SAS
# http://www.ulteo.com
# Author Gauvain POCENTEK <gauvain@ulteo.com> 2008
# Author Julien LANGLOIS <julien@ulteo.com> 2008, 2010
#
# All rights reserved.
### BEGIN INIT INFO
# Provides:          ulteo-ovd-slaveserver
# Required-Start:    $network xrdp
# Required-Stop:     $network xrdp
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Ulteo OVD slave server
# Description:       Start Ulteo OVD slave server
### END INIT INFO

. /lib/lsb/init-functions

NAME="Ulteo OVD SlaveServer"
PROGRAM=ulteo-ovd-slaveserver
PIDFILE=/var/run/ovd-slaveserver.pid

waitpid() {
	local pid=$1
	local timeout=$2
	local t0=$(date +"%s")
	
	while [ -d /proc/$1 ]; do
		sleep 0.5
	
		if [ -n "$timeout" ]; then
			local t1=$(date +"%s")
			[ $(($t1-$t0)) -gt $2 ] && return 1
		fi
	done
	
	return 0
}

do_start () {
	log_begin_msg "Starting $NAME"
	
	if [ -f $PIDFILE ]; then
		if ps $(cat $PIDFILE); then
			log_warning_msg "already running"
			log_end_msg 1
			return
		else
			rm $PIDFILE
		fi
	fi
	
	$PROGRAM --daemonize --pid-file $PIDFILE > /dev/null 2>&1
	log_end_msg 0
}

do_stop () {
	log_begin_msg "Stopping $NAME"
	
	if [ ! -f $PIDFILE ]; then
		log_warning_msg "NOT RUNNING"
		return 0
	fi
	
	pidofproc -p $PIDFILE >/dev/null
	if [ $? -ne 0 ]; then
		log_warning_msg "NOT RUNNING"
		rm $PIDFILE
	
	else
		local pid=$(pidofproc -p $PIDFILE)
		kill $pid
		waitpid $pid 10
		if [ $? -eq 1 ]; then
			log_warning_msg "Force kill"
			kill -9 $pid
			rm $PIDFILE
		fi
	fi
	
	
	log_end_msg 0
}

case $1 in
	start)
		do_start;;
	
	stop)
		do_stop;;
	
	restart|force-reload)
		do_stop
		sleep 0.2
		do_start
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|force-reload|restart}";;
esac

