#!/bin/sh

# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

debconf-get-selections | grep -e "^ulteo-ovd" -e "^mysql-server" | chroot /target debconf-set-selections
chroot /target apt-cdrom add

apt_install_direct=/var/lib/ubiquity/apt-install-direct
is_apt_install_direct=[ -f $apt_install_direct ]
test $is_apt_install_direct || touch $apt_install_direct
cp /usr/lib/ubiquity/ovd-setup/initctl_hook /target/sbin/initctl
apt-install ulteo-ovd-easy-install
test $is_apt_install_direct || rm $apt_install_direct

# change /etc/issue
unset LANG
eth=$(ifconfig | grep ^eth | head -n 1 | cut -d' ' -f1)
if [ -n "$eth" ]; then
    ip=$(ifconfig $eth | sed -rn '/inet addr/ {s/.*addr:(.*)  Bcast.*/\1/;p}')
    [ -n "$ip" ] && sed -i "s/-------/${ip}/" /target/etc/issue
fi

# add ulteo repository
cat > /target/etc/apt/sources.list.d/ulteo-ovd.list << EOF
# OVD repository
deb http://archive.ulteo.com/ovd/3.0/ubuntu lucid main
EOF

exit 0
