#!/bin/sh -e

INSTALLDIR=/usr/share/ulteo-ovd

if [ "$1" = "configure" ]; then
    if ! dpkg-statoverride --list $INSTALLDIR >/dev/null 2>&1; then
        dpkg-statoverride --update --add root root 0750 $INSTALLDIR
    fi

    if ! grep "^force-confold" /etc/dpkg/dpkg.cfg >/dev/null 2>&1; then
        cat >> /etc/dpkg/dpkg.cfg <<EOF

# We will use apt in a non-interactive mode, make sure to not
# overwrite the config files
force-confold
EOF
    fi

    if [ ! -e /var/lib/ulteo/available-apps.xml ]; then
        touch /var/lib/ulteo/available-apps.xml
    fi

    # first run of desktop-files2xml
    /usr/bin/desktop-files2xml >/var/lib/ulteo/available-apps.xml 2>/dev/null || true
fi

#DEBHELPER#

exit 0
