#!/bin/sh

# Copyright (C) 2008-2011 Ulteo SAS
# http://www.ulteo.com
# Author Gauvain POCENTEK <gpocentek@linutop.com> 2008-2009
# Author Jeremy DESVAGES <jeremy@ulteo.com> 2009-2010
# Author Samuel BOVEE <samuel@ulteo.com> 2010-2011
# Author Julien LANGLOIS <julien@ulteo.com> 2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

### BEGIN INIT INFO
# Provides:          ulteo-ovd-subsystem
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      apache2
# Should-Stop:       apache2
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Start Ulteo OVD subsystem
# Description:       Start Ulteo OVD subsystem and needed services
### END INIT INFO

. /etc/rc.status

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

# First reset status of this service
rc_reset

# useless for now...
[ -f $sysconfdir/ulteo-ovd-subsystem ] && . $sysconfdir/ulteo-ovd-subsystem
[ "$START" = no ] && exit 0

[ -f /etc/default/ulteo-ovd-subsystem ] && . /etc/default/ulteo-ovd-subsystem
[ -f /etc/ulteo/subsystem.conf ] && . /etc/ulteo/subsystem.conf

do_start() {
    [ -d "$CHROOTDIR" ] || return 1

    # hack to hide a cups issue
    MODKERNELDIR=$CHROOTDIR/lib/modules/$(uname -r)
    mkdir -p $MODKERNELDIR
    touch $MODKERNELDIR/modules.dep

    mount -t proc none $CHROOTDIR/proc 2>/dev/null
    mount -t devpts none $CHROOTDIR/dev/pts 2>/dev/null
    mount -t tmpfs none $CHROOTDIR/dev/shm 2>/dev/null

    uchroot service cups start
    uchroot service xrdp start
    uchroot service smbd start
    uchroot service apache2 start
    uchroot service ulteo-ovd-slaveserver start
}

do_stop() {
    [ -d "$CHROOTDIR" ] || return 1

    uchroot service ulteo-ovd-slaveserver stop
    uchroot service apache2 stop
    uchroot service smbd stop
    uchroot service xrdp stop
    uchroot service cups stop

    umount $CHROOTDIR/dev/shm 2>/dev/null
    umount $CHROOTDIR/dev/pts 2>/dev/null
    umount $CHROOTDIR/proc 2>/dev/null
}

case $1 in
    start)
        do_start
        echo -n "Starting Ulteo OVD subsystem"
        rc_status -v
        ;;
    stop)
        do_stop
        echo -n "Stopping Ulteo OVD subsystem"
        rc_status -v
        ;;
    restart|reload|force-reload)
        do_stop && sleep 1 && do_start
        echo -n "Re-starting Ulteo OVD subsystem"
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0
