#!/bin/sh
# Copyright (c) 2010 Ulteo SAS.
#
# Author: Julien LANGLOIS <julien@ulteo.com>
#         Samuel BOVEE <samuel@ulteo.com>
#
### BEGIN INIT INFO
# Provides:          ulteo-ovd-subsystem
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      apache2
# Should-Stop:       apache2
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Ulteo OVD subsystem
# Description:       Start Ulteo OVD subsystem and needed services
### END INIT INFO

. /etc/rc.status

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

# First reset status of this service
rc_reset

# useless for now...
[ -f $sysconfdir/ulteo-ovd-subsystem ] && . $sysconfdir/ulteo-ovd-subsystem
[ "$START" = no ] && exit 0

CONFFILE=/etc/ulteo/subsystem.conf
[ -f "$CONFFILE" ] && . $CONFFILE
[ -z "$CHROOTDIR" ] && CHROOTDIR=/opt/ulteo

test -d "$CHROOTDIR" || exit 5

do_start() {
    [ -d "$CHROOTDIR" ] || return 1

    # hack to hide a cups issue
    MODKERNELDIR=$CHROOTDIR/lib/modules/$(uname -r)
    mkdir -p $MODKERNELDIR
    touch $MODKERNELDIR/modules.dep

    mount -t proc none $CHROOTDIR/proc
    mount -t devpts none $CHROOTDIR/dev/pts

    chroot $CHROOTDIR /etc/init.d/cups start
    chroot $CHROOTDIR /etc/init.d/xrdp start
    chroot $CHROOTDIR service smbd start
    chroot $CHROOTDIR /etc/init.d/apache2 start
    chroot $CHROOTDIR /etc/init.d/ovdSlaveServer start
}

do_stop() {
    [ -d "$CHROOTDIR" ] || return 1

    chroot $CHROOTDIR /etc/init.d/ovdSlaveServer stop
    chroot $CHROOTDIR /etc/init.d/apache2 stop
    chroot $CHROOTDIR service smbd stop
    chroot $CHROOTDIR /etc/init.d/xrdp stop
    chroot $CHROOTDIR /etc/init.d/cups stop

    umount $CHROOTDIR/dev/pts || true
    umount $CHROOTDIR/proc || true
}

case $1 in
    start)
        do_start
        echo -n "Starting Ulteo OVD subsystem"
        rc_status -v
        ;;
    stop)
        do_stop
        echo -n "Stopping Ulteo OVD subsystem"
        rc_status -v
        ;;
    restart|reload|force-reload)
        do_stop && sleep 1 && do_start
        echo -n "Re-starting Ulteo OVD subsystem"
        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0
