#!/bin/sh

ICONPATH=/usr/share/icons

xdg-icon-resource install --size 32 --mode system $ICONPATH/ulteo.png ulteo-ovd-native-client
xdg-icon-resource install --size 128 --mode system $ICONPATH/ulteo-128.png ulteo-ovd-native-client

#DEBHELPER#

exit 0
