#!/bin/sh

# Copyright (C) 2011 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2011
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


if [ -f /etc/default/ulteo-ovd-subsystem ]; then
    . /etc/default/ulteo-ovd-subsystem
else
    echo "default configuration file is missing" >&2
    exit 127
fi
[ -f /etc/ulteo/subsystem.conf ] && . /etc/ulteo/subsystem.conf

if [ -z "$CHROOTLANG" -o -z "$CHROOTDIR" ]; then
    echo "required option with empty value" >&2
    exit 126
fi

env LANG=$CHROOTLANG LC_ALL=$CHROOTLANG chroot $CHROOTDIR $*
