#!/bin/sh

# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

args="--without-libchart"

# get module
module=ovd-session-manager
set -- $(getopt -u -l ha m: "$@")
[ $# -lt 1 ] && exit 1
while [ $# -gt 0 ]
do
    case "$1" in
        -m) module="$2" ; shift ;;
        --ha) args+=" --with-ha" ;;
        --) shift; break ;;
        *)  break ;;
    esac
    shift
done

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    if [ -d .svn ]; then
      revision=$(LC_ALL=C svn info . | awk '/^Revision: / {printf "%05d\n", $2}')
    else
      revision=0
    fi
    version="99.99.svn$revision"
fi

sed "s/@MODULE@/${module}/g" < configure.ac.in | \
sed "s/@VERSION@/${version}/g" > configure.ac

autoreconf -vfi && ./configure $args
