#!/bin/sh

args="--without-libchart"

# get module
module=ovd-session-manager
set -- $(getopt -u -l ha m: "$@")
[ $# -lt 1 ] && exit 1
while [ $# -gt 0 ]
do
    case "$1" in
        -m) module="$2" ; shift ;;
        --ha) args+=" --with-ha" ;;
        --) shift; break ;;
        *)  break ;;
    esac
    shift
done

# get version
if [ -n "$OVD_VERSION" ]; then
    version="$OVD_VERSION"
else
    if [ -d .svn ]; then
      revision=$(LC_ALL=C svn info . | awk '/^Revision: / {printf "%05d\n", $2}')
    else
      revision=0
    fi
    version="99.99.svn$revision"
fi

sed "s/@MODULE@/${module}/g" < configure.ac.in | \
sed "s/@VERSION@/${version}/g" > configure.ac

autoreconf -vfi && ./configure $args
