#!/bin/sh

# Copyright (C) 2010-2012 Ulteo SAS
# http://www.ulteo.com
# Author Vincent ROULLIER <v.roullier@ulteo.com> 2013
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

ARCH=$1
[ -z "$ARCH" ] && ARCH=$(getconf LONG_BIT)

echo "* librdp.so ${ARCH}bits"

# for packaging
if which schroot > /dev/null && schroot -l | cut -d ':' -f2 | grep -q "^lucid$ARCH$"; then
   if [ -d "build" ]; then
   	  rm -rf  "build"
		  fi
		  mkdir build
		  cd build
    schroot -q -c lucid$ARCH -- cmake ../ -DSTATIC_COMPILATION=ON && \
    schroot -q -c lucid$ARCH -- cmake --build . --config Release  2>/dev/null

# for devs
else
		if [ -d "build" ]; then
		   rm -rf  "build"
		   fi
		   mkdir build
		   cd build
    cmake ..  && cmake --build . --config Release 2>/dev/null
fi
