#!/bin/sh

# $XDG_CONFIG_HOME defines the base directory relative to which user specific
# configuration files should be stored. If $XDG_CONFIG_HOME is either not set
# or empty, a default equal to $HOME/.config should be used.
if test "x$XDG_CONFIG_HOME" = "x" ; then
  XDG_CONFIG_HOME=$HOME/.config
fi
[ -d "$XDG_CONFIG_HOME" ] || mkdir "$XDG_CONFIG_HOME"

# $XDG_CACHE_HOME defines the base directory relative to which user specific
# non-essential data files should be stored. If $XDG_CACHE_HOME is either not
# set or empty, a default equal to $HOME/.cache should be used.
if test "x$XDG_CACHE_HOME" = "x" ; then
  XDG_CACHE_HOME=$HOME/.cache
fi
[ -d "$XDG_CACHE_HOME" ] || mkdir "$XDG_CACHE_HOME"

# For now, start with an empty list
XRESOURCES=""

# Has to go prior to merging Xft.xrdb, as its the "Defaults" file
test -r "/etc/xdg/xfce4/Xft.xrdb" && XRESOURCES="$XRESOURCES /etc/xdg/xfce4/Xft.xrdb"
test -r $HOME/.Xdefaults && XRESOURCES="$XRESOURCES $HOME/.Xdefaults"

BASEDIR=$XDG_CONFIG_HOME/xfce4
if test -r "$BASEDIR/Xft.xrdb"; then
  XRESOURCES="$XRESOURCES $BASEDIR/Xft.xrdb"
elif test -r "$XFCE4HOME/Xft.xrdb"; then
  mkdir -p "$BASEDIR"
  cp "$XFCE4HOME/Xft.xrdb" "$BASEDIR"/
  XRESOURCES="$XRESOURCES $BASEDIR/Xft.xrdb"
fi

# start with a white background
xsetroot -cursor_name watch -solid white

# merge in X cursor settings
if test -r "$BASEDIR/Xcursor.xrdb"; then
  XRESOURCES="$XRESOURCES $BASEDIR/Xcursor.xrdb"
elif test -r "/etc/xdg/xfce4/Xcursor.xrdb"; then
  XRESOURCES="$XRESOURCES /etc/xdg/xfce4/Xcursor.xrdb"
fi

# ~/.Xresources contains overrides to the above
test -r "$HOME/.Xresources" && XRESOURCES="$XRESOURCES $HOME/.Xresources"

# load all X resources (adds /dev/null to avoid an empty list that would hang the process)
cat /dev/null $XRESOURCES | xrdb -nocpp -merge -

# Use dbus-launch if installed.
if test x"$DBUS_SESSION_BUS_ADDRESS" = x""; then
  dbuslaunch=`which dbus-launch`
  if test x"$dbuslaunch" != x"" -a x"$dbuslaunch" != x"no"; then
    eval `$dbuslaunch --sh-syntax --exit-with-session`
  fi
fi

# automatically open an application if needed
if [ -n "$DOC" ] || [ -n "$APP_ID" ]; then
  # simultate a desktop session startup
  xfsm-compat start
  xfwm4 --daemon

  if [ -n "$APP_ID" ] && [ -n "$OVD_APPS_DIR" ]; then
    CMD=$(grep "^Exec=" "$OVD_APPS_DIR/$APP_ID.desktop" | sed -e "s/^Exec=//")
  else
    CMD="xdg-open"
  fi

  if [ "$NODESKTOP" == "1" ]; then
    eval $CMD
    exit 0
  else
    eval $CMD &
  fi
fi

xfce4-session

exit 0

