#!/bin/bash

# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Arnaud LEGRAND <arnaud@ulteo.com> 2010
# Author Samuel BOVEE <samuel@ulteo.com> 2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

### BEGIN INIT INFO
# Provides:          ulteo_ha
# Required-Start:    $remote_fs $syslog $network drbd mysql apache2 heartbeat
# Required-Stop:     $remote_fs $syslog $network drbd mysql apache2 heartbeat
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop Ulteo Session Manager high availability service.
# Description:       This script is used to manage Session Manager cluster nodes (registration/unregistration). It generates configuration files.
### END INIT INFO

HA_VARLIB_DIR=/var/lib/ulteo/ovd

detect_lo() {
	losetup -a |grep "$HA_VARLIB_DIR/vbd0.bin" |cut -d ":" -f1
}


case $1 in

    start)
        service mysql stop || true
        service apache2 stop
        losetup $(losetup -f) $HA_VARLIB_DIR/vbd0.bin
    ;;

    stop)
        DRBD_LOOP=$(detect_lo)
        if [ -n "$DRBD_LOOP" ]; then
            losetup -d $DRBD_LOOP
        fi
        service mysql --full-restart
        service apache2 restart
    ;;

    *)
        echo "Usage: ulteo_ha {start|stop}"
        exit 2
    ;;

esac
exit 0
