#!/bin/bash
### BEGIN INIT INFO
# Provides:          ulteo_ha
# Required-Start:    $remote_fs $syslog $network drbd mysql apache2 heartbeat
# Required-Stop:     $remote_fs $syslog $network drbd mysql apache2 heartbeat
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/Stop Ulteo Session Manager high availability service.
# Description:       This script is used to manage Session Manager cluster nodes (registration/unregistration). It generates configuration files.
### END INIT INFO
# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Arnaud LEGRAND <arnaud@ulteo.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

set -e
unset LANG

HA_CONF_DIR=/etc/ulteo/ovd/ha
HA_DATA_DIR=/usr/share/ulteo/ovd/ha
HA_VARLIB_DIR=/var/lib/ulteo/ovd

DRBD_RESOURCE="sm0"
DRBD_CONF=/etc/drbd.d/$DRBD_RESOURCE.res
HEARTBEAT_CONF_DIR=/etc/ha.d
SM_LOG_DIR=/var/log/ulteo/sessionmanager

. $HA_DATA_DIR/scripts/utils.sh

ha_make_configurations() {
    OTHER_IP=$2
	OTHER_HOSTNAME=$3
	AUTHKEY=$4

    NIC_NAME=$(grep -E "^NIC_NAME" $HA_CONF_DIR/resources.conf | sed -r "s/^NIC_NAME *= *([a-zA-Z0-9]*) ?.*$/\1/")
	GATEWAY=$(route -n | grep '^0\.0\.\0\.0[ \t]\+[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]\+[ \t]\+0\.0\.0\.0[ \t]\+[^ \t]*G[^ \t]*[ \t]' | awk '{print $2}')
	NIC_ADDR=$(ifconfig $NIC_NAME | awk -F":| +" '/inet addr/{print $4}')

    # Heartbeat authkeys conf
    sed "s/%AUTHKEY%/$AUTHKEY/" $HA_DATA_DIR/conf/authkeys > $HEARTBEAT_CONF_DIR/authkeys

    # Heartbeat conf
    sed "s/%GATEWAY%/$GATEWAY/" $HA_DATA_DIR/conf/ha.cf | \
        sed "s/%NIC_NAME%/$NIC_NAME/" | sed "s/%NIC_ADDR%/$NIC_ADDR/" | \
        sed "s/%HOSTNAME%/$HOSTNAME/" | sed "s/%SM_LOG_DIR%/$SM_LOG_DIR/" \
            > $HEARTBEAT_CONF_DIR/ha.cf
	if [ -n "$OTHER_IP" ] && [ -n "$OTHER_HOSTNAME" ]; then
        sed -i "/ucast/ a\ucast $NIC_NAME $OTHER_IP" $HEARTBEAT_CONF_DIR/ha.cf
        sed -i "/node/ a\node $OTHER_HOSTNAME" $HEARTBEAT_CONF_DIR/ha.cf
	fi

    # DRBD conf
	local device=/dev/drbd0;
	local disk=/dev/loop0;
    sed "s/%RESOURCE%/$DRBD_RESOURCE/" $HA_DATA_DIR/conf/$DRBD_RESOURCE.res | \
        sed "s/%DEVICE%/$device/" | sed "s/%LOOP%/$disk/" | \
        sed "s/%AUTH_KEY%/$AUTH_KEY/"  | sed "s/%HOSTNAME%/$HOSTNAME/" | \
        sed "s/%NIC_ADDR%/$NIC_ADDR/"  > $DRBD_CONF
	if [ -n "$OTHER_IP" ] && [ -n "$OTHER_HOSTNAME" ]; then
		echo "on $OTHER_HOSTNAME {" >> $DRBD_CONF
		echo "address   $OTHER_IP:7788;" >> $DRBD_CONF
		echo "}" >> $DRBD_CONF
	fi
	echo "}" >> $DRBD_CONF

	chmod 660 $HEARTBEAT_CONF_DIR/ha.cf $HEARTBEAT_CONF_DIR/authkeys $DRBD_CONF
}


ha_reload_master() {
    service heartbeat stop
	ha_make_configurations "$2" "$3" "$4"
    sleep 5
    service heartbeat start
}


ha_start_slave() {
    service mysql stop
    service apache2 stop
    service heartbeat stop
    rm -f /var/lib/heartbeat/crm
    ha_make_configurations "" "" "$2"
    service heartbeat restart
}


case $1 in

    reload_master|reload_master_excl)
        if [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ]; then
		    ha_reload_master "$2" "$3" "$4"
            sleep 120
        else
            echo "$1 <IP> <HOSTNAME> <AUTHKEY>"
            exit 2
        fi
    ;;

    register)
        if [ -n "$4" ]; then
		    ha_start_slave "$4"
            sleep 120
        else
            echo "$1 <AUTHKEY>"
            exit 2
        fi
    ;;

    reload_vip)
        VIP="$2"
		if [ -n $VIP ]; then
		    valid_ip $VIP && \
			    crm_resource --resource vip --set-parameter ip --parameter-value $VIP
            sleep 120
        else
            echo "reload_vip <VIP>"
            exit 2
        fi
    ;;

    start)
        service mysql stop
        service apache2 stop
        losetup $(losetup -f) $HA_VARLIB_DIR/vbd0.bin
    ;;

    stop)
        losetup -d $DRBD_LOOP
        service mysql restart
        service apache2 restart
    ;;

    status)
        echo "Status can not be performed !"
    ;;

    *)
		echo "Usage: ./ulteo_ha {start|stop|restart}"
        echo "Please, don't use it manually !"
        exit 2
    ;;

esac
exit 0
