#!/bin/bash

# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Arnaud LEGRAND <arnaud@ulteo.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

set -e
unset LANG
export PATH=$PATH/usr/local/bin:/usr/sbin:/sbin:/bin:/usr/bin

CONFDIR=/etc/ulteo/ovd/ha
DATADIR=/usr/share/ulteo/ovd/ha
LOGDIR=/var/log/ulteo/sessionmanager

VBD_BIN=$CONFDIR/vbd0.bin

# load HA utils functions
. $DATADIR/scripts/utils.sh

ha_make_configurations() {
    OTHER_IP=$2
	OTHER_HOSTNAME=$3
	AUTHKEY=$4

	HEARTBEAT_HA_CONF=/etc/ha.d/ha.cf
	HEARTBEAT_AUTHKEYS_CONF=/etc/ha.d/authkeys
    DRBD_RESOURCE="sm0"
	DRBD_CONF=/etc/drbd.d/$DRBD_RESOURCE.res

	GATEWAY=`route -n | grep '^0\.0\.\0\.0[ \t]\+[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]\+[ \t]\+0\.0\.0\.0[ \t]\+[^ \t]*G[^ \t]*[ \t]' | awk '{print $2}'`
	NIC_NAME="eth0"
	NIC_ADDR=`ifconfig $NIC_NAME | awk -F":| +" '/inet addr/{print $4}'`

	# load dynamic values
	. $CONFDIR/resources.conf

    # Heartbeat authkeys conf
    sed "s/%AUTHKEY%/$AUTHKEY/" $DATADIR/conf/authkeys > $HEARTBEAT_AUTHKEYS_CONF

    # Heartbeat conf
    sed "s/%GATEWAY%/$GATEWAY/" $DATADIR/conf/ha.cf | \
        sed "s/%NIC_NAME%/$NIC_NAME/" | sed "s/%NIC_ADDR%/$NIC_ADDR/" | \
        sed "s/%HOSTNAME%/$HOSTNAME/" | sed "s/%LOGDIR%/$SM_LOGDIR/" \
            > $HEARTBEAT_HA_CONF
	if [ -n "$OTHER_IP" ] && [ -n "$OTHER_HOSTNAME" ]; then
        sed -i "/ucast/ a\ucast $NIC_NAME $OTHER_IP" $HEARTBEAT_HA_CONF
        sed -i "/node/ a\node $OTHER_HOSTNAME" $HEARTBEAT_HA_CONF
	fi

    # DRBD conf
	local device=/dev/drbd0;
	local disk=/dev/loop0;
    sed "s/%RESOURCE%/$DRBD_RESOURCE/" $DATADIR/conf/$DRBD_RESOURCE.res | \
        sed "s/%DEVICE%/$device/" | sed "s/%LOOP%/$disk/" | \
        sed "s/%AUTH_KEY%/$AUTH_KEY/"  | sed "s/%HOSTNAME%/$HOSTNAME/" | \
        sed "s/%NIC_ADDR%/$NIC_ADDR/"  > $DRBD_CONF
	if [ -n "$OTHER_IP" ] && [ -n "$OTHER_HOSTNAME" ]; then
		echo "on $OTHER_HOSTNAME {" >> $DRBD_CONF
		echo "address   $OTHER_IP:7788;" >> $DRBD_CONF
		echo "}" >> $DRBD_CONF
	fi
	echo "}" >> $DRBD_CONF

	chmod 660 $HEARTBEAT_HA_CONF $HEARTBEAT_AUTHKEYS_CONF $DRBD_CONF
}


ha_reload_master() {
    service heartbeat stop
	ha_make_configurations "$2" "$3" "$4"
    sleep 5
    service heartbeat start
}


ha_start_slave() {
    service mysql stop
    service apache2 stop
    service heartbeat stop
    rm -f /var/lib/heartbeat/crm
    ha_make_configurations "" "" "$2"
    service heartbeat restart
}


case $1 in

    reload_master|reload_master_excl)
        if [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ]; then
		    $1 "$2" "$3" "$4"
            sleep 120
        else
            echo "$1 <IP> <HOSTNAME> <AUTHKEY>"
            exit 2
        fi
    ;;

    register)
        if [ -n "$4" ]; then
		    register "$4"
            sleep 120
        else
            echo "$1 <AUTHKEY>"
            exit 2
        fi
    ;;

    reload_vip)
		if [ -n "$2" ]; then
		    VIP=$2
		    valid_ip $VIP && \
			    crm_resource --resource vip --set-parameter ip --parameter-value $VIP
            sleep 120
        else
            echo "reload_vip <VIP>"
            exit 2
        fi
    ;;

    start)
        service mysql stop
        service apache2 stop
        losetup $(losetup -f) $VBD_BIN
    ;;

    stop)
        #TODO: error -> wrong loop
        losetup -d $DRBD_LOOP
        service mysql restart
        service apache2 restart
    ;;

    status)
        echo "Status can not be performed !"
    ;;

    *)
		echo "Usage: ./ulteo_ha {start|stop|restart}"
        echo "Please, don't use it manually !"
        exit 2
    ;;

esac
exit 0
