#! /usr/bin/python
# -*- coding: UTF-8 -*-

# Copyright (C) 2011-2013 Ulteo SAS
# http://www.ulteo.com
# Author Julien LANGLOIS <julien@ulteo.com> 2011
# Author David PHAM-VAN <d.pham-van@ulteo.com> 2013
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import os
import re
import time

path = os.path.dirname( os.path.realpath( __file__ ) )

# Detect the version
if os.environ.has_key("OVD_VERSION"):
	version = os.environ["OVD_VERSION"]
else:
	version = file("VERSION", "r").readline().strip()
	version += "~dev"

version_strict = ".".join([p for p in (re.split("[^\d\.]", version)[0]+".0"*4).split(".")  if p.isdigit()][:4])

for name in ["ressources.rc"]:
	f = file(os.path.join(path, name+".in"), "r")
	content = f.read()
	f.close()
	
	content = content.replace("@VERSION@", version)
	content = content.replace("@VERSION_STYLE_C@", version_strict.replace(".", ","))
	content = content.replace("@YEAR@", time.strftime("%Y"))
	
	f = file(os.path.join(path, name), "w")
	f.write(content)
	f.close()
