#!/bin/sh -e

. /usr/share/debconf/confmodule

case "$1" in

    purge)
        db_get ulteo-ovd-easy-install/mysql_dbserver && dbserver=$RET
        if ! db_get ulteo-ovd-debconf-database/mysql_root_password; then
            # ask to the user the mysql admin password
            while true; do
                db_input critical ulteo-ovd-easy-install/mysql_dbrootpass || true
                db_go

                db_get ulteo-ovd-easy-install/mysql_dbrootpass
                if echo "quit" | mysql --silent --user=root --password=$RET 2>/dev/null; then
                    db_reset ulteo-ovd-easy-install/mysql_dbrootpass
                    dbpasswd=
                    break
                else
                    db_fset ulteo-ovd-easy-install/mysql_dbrootpass seen false || false
                    db_input high ulteo-ovd-easy-install/wrong_msql_password || true
                fi
            done
        fi
        dbadmin=root
        dbadmpass=$RET

        db_get ulteo-ovd-easy-install/mysql_dbname && dbname=$RET
        . /usr/share/wwwconfig-common/mysql-dropdb.sh

        db_get ulteo-ovd-easy-install/mysql_dbuser && dbuser=$RET
        . /usr/share/wwwconfig-common/mysql-dropuser.sh
    ;;

    abort-*)
        exit 1
    ;;

    *) ;;
esac

#DEBHELPER#

exit 0
