#! /usr/bin/python

import os
import sys
import pysvn
from subprocess import Popen

path = os.path.dirname( os.path.realpath( __file__ ) )

# Detect the version
if os.environ.has_key("OVD_VERSION"):
	version = os.environ["OVD_VERSION"]
else:
	c = pysvn.Client()
	revision = c.info(path)["revision"].number
	version = "99.99+svn%05d"%(revision)

f = file(os.path.join(path, "build.xml.in"), "r")
content = f.read()
f.close()

content = content.replace("@VERSION@", str(version))

f = file(os.path.join(path, "build.xml"), "w")
f.write(content)
f.close()

if sys.platform == "linux2":
    p = Popen("./autogen", cwd=os.path.join(path, "libXClientArea"))
    p.wait()
