#! /usr/bin/python

import os
import sys
import pysvn
import shutil
from subprocess import Popen

path = os.path.dirname( os.path.realpath( __file__ ) )

# Detect the version
if os.environ.has_key("OVD_VERSION"):
	version = os.environ["OVD_VERSION"]
else:
	c = pysvn.Client()
	revision = c.info(path)["revision"].number
	version = "99.99+svn%05d"%(revision)

f = file(os.path.join(path, "build.xml.in"), "r")
content = f.read()
f.close()

content = content.replace("@VERSION@", str(version))

f = file(os.path.join(path, "build.xml"), "w")
f.write(content)
f.close()

if sys.platform == "linux2":
    libdir = os.path.join(path, "libXClientArea")
    dst = os.path.join(path, "required_libraries", "libXClientArea")
    if os.path.exists(dst):
        shutil.rmtree(dst)
    p = Popen("./autogen", cwd=libdir)
    p.wait()
    os.makedirs(dst)
    for arch in ['32','64']:
        src = os.path.join(libdir, arch)
        if os.path.exists(os.path.join(src, "libXClientArea.so")):
            shutil.move(src, dst)
    print libdir
    p = Popen("make clean", cwd=libdir, shell=True)
    p.wait()
