#!/bin/sh

if [ -d .svn ]; then
    revision=$(LC_ALL=C svn info build.xml.in | awk '/^Revision: / {printf "%05d\n", $2}')
elif [ -n "OVD_VERSION" ]; then
    revision="$OVD_VERSION"
else
    revision="99.99"
fi

LANG_STR=""
for i in po/*.po; do
    p=$(basename $i .po)
    
    LANG_STR="$LANG_STR <exec executable=\"msgfmt\" dir=\"${PWD}\"> <arg value=\"--java2\"/> <arg value=\"-d\"/> <arg value=\"ressources\"/> <arg value=\"-r\"/> <arg value=\"Messages\"/> <arg value=\"-l\"/> <arg value=\"$p\"/> <arg value=\"$i\"/> </exec>"
done


sed -e "s/@REVISION@/${revision}/g" \
    -e "s#@MESSAGE_LANGS@#${LANG_STR}#g" \
        < "build.xml.in" > "build.xml"


