#! /usr/bin/python

import os
import pysvn
import glob

# Detect the version
if os.environ.has_key("OVD_VERSION"):
	version = os.environ["OVD_VERSION"]

else:
	c = pysvn.Client()
	revision = c.info(".")["revision"].number
	version = "99.99~trunk+svn%05d"%(revision)

langs = []
for pofile in glob.glob("po/*.po"):
	name = os.path.basename(pofile)[:-3]

	node = '<exec executable="msgfmt" dir="%s">'%(os.path.abspath(os.path.curdir))
	node+= '<arg value="--java2"/>'
	node+= '<arg value="-d"/>'
	node+= '<arg value="ressources"/>'
 	node+= '<arg value="-r"/>'
 	node+= '<arg value="Messages"/>'
 	node+= '<arg value="-l"/>'
 	node+= '<arg value="%s"/>'%(name)
 	node+= '<arg value="%s"/>'%(pofile)
 	node+= '</exec>'

	langs.append(node)


f = file("build.xml.in", "r")
content = f.read()
f.close()

content = content.replace("@VERSION@", str(version))
content = content.replace("@MESSAGE_LANGS@", "\n".join(langs))

f = file("build.xml", "w")
f.write(content)
f.close()
