#!/bin/sh -e
# vim: set syntax=sh:

. /usr/share/debconf/confmodule
db_version 2.0

if [ "$1" = "configure" ] && [ -z "$2" ] || [ "$1" = "reconfigure" ]; then

db_get od/sessionmanager/oem || false
if [ "$RET" = "true" ]; then
  db_set od/sessionmanager/mysql/configure true
    db_input medium od/sessionmanager/mysql/configure || true
  db_go || true

  db_get od/sessionmanager/mysql/configure || true
  if [ "$RET" = "true" ]; then
    db_input critical od/sessionmanager/mysql/dbserver || true
    db_input critical od/sessionmanager/mysql/dbadmin || true
    db_input critical od/sessionmanager/mysql/dbadmpass || true
    db_input critical od/sessionmanager/mysql/dbuser || true
    db_input critical od/sessionmanager/mysql/dbpass || true
    db_input medium od/sessionmanager/mysql/dbname || true
    db_go || true
  fi
fi

  db_input critical od/sessionmanager/admin_login || true
  db_go
  while :; do
    db_input critical od/sessionmanager/admin_password || true
    db_go
    db_get od/sessionmanager/admin_password
    ROOT_PWD="$RET"
    db_input critical od/sessionmanager/admin_password_again || true
    db_go
    db_get od/sessionmanager/admin_password_again
    if [ "$RET" = "$ROOT_PWD" ]; then
      ROOT_PW=""
      break
    fi
    db_fset od/sessionmanager/password_mismatch seen false
    db_input critical od/sessionmanager/password_mismatch
    db_set od/sessionmanager/admin_password ""
    db_set od/sessionmanager/admin_password_again ""
    db_go
  done

  if [ ! -e /usr/share/ulteo/sessionmanager/base.tar.gz ]; then
    db_input critical od/sessionmanager/download_tarball || true
    db_go
  fi
fi

db_stop

exit 0
