#!/bin/sh -e
# vim: set syntax=sh:

. /usr/share/debconf/confmodule
db_version 2.0

if [ "$1" = "configure" ] && [ -z "$2" ] || [ "$1" = "reconfigure" ]; then
  db_input critical od/sessionmanager/admin_login || true
  db_go

  while :; do
    db_input critical od/sessionmanager/admin_password || true
    db_go
    db_get od/sessionmanager/admin_password
    ROOT_PWD="$RET"
    db_input critical od/sessionmanager/admin_password_again || true
    db_go
    db_get od/sessionmanager/admin_password_again
    if [ "$RET" = "$ROOT_PWD" ]; then
      ROOT_PW=""
      break
    fi
    db_fset od/sessionmanager/password_mismatch seen false
    db_input critical od/sessionmanager/password_mismatch
    db_set od/sessionmanager/admin_password ""
    db_set od/sessionmanager/admin_password_again ""
    db_go
  done

  db_input critical od/sessionmanager/download_tarball || true
  db_go
fi

db_stop

exit 0
