#!/bin/sh -e

. /usr/share/debconf/confmodule

# Do nothing if we're not installing
if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
    exit 0
fi

WGETARGS="--tries=3 --timeout=60"
CHROOT_TARGET=/usr/share/ulteo/sessionmanager/base.tar.gz

CONFFILE="/etc/ulteo/sessionmanager/config.inc.php"

apache_config()
{
    if [ ! -e /etc/apache2/conf.d/sessionmanager ]; then
        ln -s /etc/ulteo/sessionmanager/apache2.conf \
            /etc/apache2/conf.d/sessionmanager

        if apache2ctl configtest 2>/dev/null; then
            invoke-rc.d apache2 reload || true
        else
            echo "Your apache2 configuration is broken, so we're not restarting it for you."
        fi
    fi
}

gen_conf()
{
    db_get od/sessionmanager/admin_login || true
    LOGIN="$RET"
    db_get od/sessionmanager/admin_password || true
    PASSWD=$(echo -n $RET | md5sum | cut -d " " -f 1)
    # clear the password
    unset RET
    db_set od/sessionmanager/admin_password ""

    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_LOGIN.*').*('.*)$,\1$LOGIN\2," $CONFFILE
    sed -r -i "s,^(.*SESSIONMANAGER_ADMIN_PASSWORD.*').*('.*)$,\1$PASSWD\2," $CONFFILE

    # TODO : add mysql database config
}

# Configure Mysql Database
db_get od/sessionmanager/oem
if [ "$RET" = true ];then
db_get od/sessionmanager/mysql/configure
    if [ "$RET" = true ]; then

	# get the answers to our questions
	db_get od/sessionmanager/mysql/dbserver
	dbserver=$RET
	db_get od/sessionmanager/mysql/dbadmin
	dbadmin=$RET
	db_get od/sessionmanager/mysql/dbadmpass
	dbadmpass=$RET
	db_reset od/sessionmanager/mysql/dbadmpass
	db_get od/sessionmanager/mysql/dbname
	dbname=$RET
	db_get od/sessionmanager/mysql/dbuser
	dbuser=$RET
	db_get od/sessionmanager/mysql/dbpass
	dbpass=$RET
	db_reset od/sessionmanager/mysql/dbpass

	# create the database
	. /usr/share/wwwconfig-common/mysql-createdb.sh
	# create user
	. /usr/share/wwwconfig-common/mysql-createuser.sh
   fi
fi



# set the configuration if we install
gen_conf
chown root:www-data $CONFFILE
chmod 0640 $CONFFILE

mkdir -p /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
chown root:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
chmod 2770 /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager

# get the chroot
db_get od/sessionmanager/download_tarball || true
URL="$RET"
if [ ! -e $CHROOT_TARGET ]; then
	if [ x"$URL" != x"" ]; then
    	wget $WGETARGS $URL -O $CHROOT_TARGET || echo "Unable to retrieve the chroot archive. You need to download it manually as $CHROOT_TARGET, or use the 'sm-config' script."
	fi
fi

apache_config

#DEBHELPER#

exit 0
