#!/bin/sh -e

CONFFILE="/etc/ulteo/sessionmanager/config.inc.php"
if [ "$1" = "purge" ]; then
    rm -rf /var/spool/ulteo/sessionmanager
    rm -rf /var/log/ulteo/sessionmanager
fi

#DEBHELPER#

exit 0
