#!/bin/sh -e

. /usr/share/debconf/confmodule

mkdir -p /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
chown -R www-data:www-data /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager
chmod 2770 /var/spool/ulteo/sessionmanager /var/log/ulteo/sessionmanager

# Do nothing if we're not installing
if [ "$1" != "configure" ] || ([ -n "$2" ] && [ -z "$DEBCONF_RECONFIGURE" ]); then
    exit 0
fi

# Configure Mysql Database
db_get ulteo-ovd-session-manager/oem
if [ "$RET" = true ];then
db_get ulteo-ovd-session-manager/mysql_configure
    if [ "$RET" = true ]; then

	# get the answers to our questions
	db_get ulteo-ovd-session-manager/mysql_dbserver
	dbserver=$RET
	db_get ulteo-ovd-session-manager/mysql_dbadmin
	dbadmin=$RET
	db_get ulteo-ovd-session-manager/mysql_dbadmpass
	dbadmpass=$RET
	db_reset ulteo-ovd-session-manager/mysql_dbadmpass
	db_get ulteo-ovd-session-manager/mysql_dbname
	dbname=$RET
	db_get ulteo-ovd-session-manager/mysql_dbuser
	dbuser=$RET
	db_get ulteo-ovd-session-manager/mysql_dbpass
	dbpass=$RET
	db_reset ulteo-ovd-session-manager/mysql_dbpass

	# create the database
	. /usr/share/wwwconfig-common/mysql-createdb.sh
	# create user
	. /usr/share/wwwconfig-common/mysql-createuser.sh

   fi
fi

#DEBHELPER#

exit 0
