#!/bin/sh -e

INSTALLDIR=/usr/share/ulteo-ovd

if [ "$1" = "purge" ]; then
    if dpkg-statoverride --list $INSTALLDIR >/dev/null 2>&1; then
        dpkg-statoverride --remove $INSTALLDIR
    fi

    OOOWRAPPER=/usr/lib/openoffice/program/soffice
    if dpkg-divert --list | grep -q $OOOWRAPPER; then
        dpkg-divert --package ulteo-ovd-application-server-daemon --remove \
            --rename --divert $OOOWRAPPER.diverted $OOOWRAPPER
    fi
fi

#DEBHELPER#

exit 0

