
DATA=\
	authentication.png \
	desktop.png \
	install01.png \
	install02.png \
	install03.png \
	install04.png \
	loading.png \
	more_options_auto.png \
	started.png

all:

install:
	install -d 		$(DIST)
	install $(DATA)		$(DIST)


