
DATA=\
	applications.png \
	configuration.png \
	servers.png \
	sharedfolder1.png \
	sharedfolder2.png \
	sharedfolder3.png \
	status.png \
	upgrade.png \
	users.png \

all:

install:
	install -d 		$(DIST)
	install $(DATA)		$(DIST)
