#!/bin/sh

# for packaging
if which schroot > /dev/null;  then
    ARCHS="32 64"
    for arch in $ARCHS; do
        if schroot -l | grep lucid$arch; then
            schroot -c lucid$arch -- make clean
            schroot -c lucid$arch -- make STATIC=yes
        fi
    done
fi

# for devs
[ ! -f $(getconf LONG_BIT)/libXClientArea.so ] && make clean && make
