#!/bin/sh

# Copyright (C) 2010 Ulteo SAS
# http://www.ulteo.com
# Author Samuel BOVEE <samuel@ulteo.com> 2010
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# for packaging
if which schroot > /dev/null;  then
    ARCHS="32 64"
    for arch in $ARCHS; do
        echo "* libXClientArea.so ${arch}bits"
        if schroot -l | grep -q lucid$arch; then
            schroot -c lucid$arch -- make -s clean
            schroot -c lucid$arch -- make -s STATIC=yes
        fi
    done
fi

# for devs
ARCH=$(getconf LONG_BIT)
if [ ! -f $ARCH/libXClientArea.so ]; then
    echo "* libXClientArea.so ${ARCH}bits"
    make -s clean && make -s
fi
