.TH  STARTOVDAPPS 1 "February 04, 2010" "Version 1.0" "OVD startovdapp Manual"
.SH NAME 
startovdapp \- an OVD command...
.SH SYNOPSIS
.B startovdapp
[\fB-options\fP|\fB...\fP]
.SH DESCRIPTION
\fBstartovdapp\fP ...
.SH OPTIONS
The following options are supported:
.SH LICENCE
Copyright (c) 2010 Ulteo SAS 
.br
This software is released under the GNU General Public License. Please
read the COPYING file for more information. 
.SH REPORTING BUGS
Please send a report to <report-ovd-bugs@ulteo.com>
.SH AUTHOR
Written by \fBSamuel Bovée\fP.
