#! /usr/bin/env python
# Copyright (C) 2008 Ulteo SAS
# http://www.ulteo.com
# Author Julien LANGLOIS <julien@ulteo.com>
#
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# of the License
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import commands
import ConfigParser
import sys, os
from xml.dom import minidom
from xml.parsers.expat import ExpatError

class Application(dict):
    def __init__(self, directory):
        self.directory = directory

    def fromXmlNode(self, doc):
        self['Name'] = doc.getAttribute("name")
        self['Comment'] = doc.getAttribute("description")
        self.filename = doc.getAttribute("desktopfile")

        if ('\\' in self.filename):
            tmp = self.filename.replace('\\', '/')
        else:
            tmp = self.filename

        self.basename = os.path.basename(tmp)
        if (self.basename.endswith('.lnk')):
            self.basename = self.basename[:-4]+'.desktop'
        self.target = os.path.join(self.directory, self.basename)

        execNode = doc.getElementsByTagName('executable')[0]
        self['Exec'] = 'startovdapp "%s" "%s"'%(self.target,execNode.getAttribute("command"))
        self['Icon'] = execNode.getAttribute("icon")

        if (self.filename.endswith('.lnk')):
            self['Exec'] = 'rdesktop -l "%s" "%s"'%(execNode.getAttribute("command"),self.filename)
            self['Icon'] = 'windows-%s.png'%(doc.getAttribute("id"))


    def toDesktopFile(self):
        lines = ['[Desktop Entry]', 'Version=1.0', 'Encoding=UTF-8', 'Type=Application']

        for k,v in self.items():
            lines.append(k+'='+v)

        lines = [e+"\n" for e in lines]

        name = os.path.join(directory, self.basename)
        f = file(name, 'wb')
        f.writelines(lines)
        f.close()


def usage():
    print>> sys.stderr, "Usage: %s file directory"%(sys.argv[0])
    print>> sys.stderr, "\tfile: a xml file that contain applications"

if len(sys.argv) < 3:
    print>> sys.stderr, "Bad argument number"
    print>> sys.stderr, ""
    usage()
    sys.exit(1)

xmlFile = sys.argv[1]
directory = sys.argv[2]

if not os.path.isfile(xmlFile):
    print>> sys.stderr, "No such file '%s'"%(xmlFile)
    print>> sys.stderr, ""
    usage()
    sys.exit(1)

if not os.path.isdir(directory):
    print>> sys.stderr, "No such directory '%s'"%(directory)
    print>> sys.stderr, ""
    usage()
    sys.exit(1)


try:
    doc = minidom.parse(xmlFile)
except ExpatError,e:
    sys.exit(1)


for node in doc.getElementsByTagName('application'):
    a = Application(directory)
    a.fromXmlNode(node)
    a.toDesktopFile()

