#!/bin/sh -e

[ "$1" != "purge" ] && exit 0

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 reload || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}

# apache2 link
rm -f /etc/apache2/sites-available/applicationserver
rm -f /etc/apache2/sites-enabled/applicationserver

reload_apache

#DEBHELPER#

exit 0
