/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_propero_rdp_Bitmap */

#ifndef _Included_net_propero_rdp_Bitmap
#define _Included_net_propero_rdp_Bitmap

JNIEXPORT jintArray JNICALL Java_net_propero_rdp_Bitmap_nRLEDecompress
  (JNIEnv *, jobject, jint, jint, jint, jbyteArray, jint);

JNIEXPORT jintArray JNICALL Java_net_propero_rdp_Bitmap_nJpegDecompress
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

#endif
